name: Linux

on:
  push:
    branches: [ master ]
    tags: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  linux-test:
    runs-on: ubuntu-20.04
    continue-on-error: true
    strategy:
      matrix:
        branch: [default]
        python-version: [3.7, 3.8, 3.9, 3.10]
    container: monetdb/dev-builds:${{ matrix.branch }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      -
        name: Setup database
        run: |
          cd test 
          ./initfarm.sh
          ./initdb.sh

      -
        name: Install Tox
        run: |
          python -m pip install tox

      -
        name: Run Tox
        run: |
          python --version
          python -m tox -e py${{ matrix.python-version}}
